IAB207/Assessment3/website/auth.py
from flask import Blueprint, render_template, request, redirect, url_for
from website.forms import LoginForm, RegisterForm
from flask_login import login_user, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from .models import db, User


auth = Blueprint(
    "auth",
    __name__,
    template_folder="templates",
    static_url_path="",
    static_folder="assets",
)


@auth.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    error = None
    if request.method == "POST" and form.validate():
        user = db.session.execute(
            db.select(User).filter(User.username == form.username.data)
        ).first()
        if user and check_password_hash(user[0].hashed_password, form.password.data):
            login_user(user[0])
            return redirect(url_for("main.index"))
        error = "Incorrect username or password"
    return render_template("login.html", form=form, error=error)


@auth.route("/register", methods=["GET", "POST"])
def register():
    register = RegisterForm()
    if register.validate_on_submit() == True:
        uname = register.username.data
        pwd = register.password.data
        email = register.email.data
        u1 = User.query.filter_by(username=uname).first()
        if u1:

            return redirect(url_for("auth.login"))
        pwd_hash = generate_password_hash(pwd)
        new_user = User(username=uname, hashed_password=pwd_hash, email=email)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for("main.index"))
    else:
        return render_template("register.html", form=register)


@auth.route("/logout", methods=["POST", "GET"])
def logout():
    logout_user()
    return redirect(url_for("main.index"))

IAB207/Assessment3/website/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from .models import Event


views = Blueprint("main", __name__)


@views.route("/")
def index():
    events = Event.query.all()
    return render_template("index.html", events=events)


@views.route("/viewall")
def all():
    events = Event.query.all()
    return render_template("showall.html", events=events)


@views.route("/myevents")
@login_required
def my():
    compuser = current_user.id
    events = Event.query.select_from(Event).filter(compuser == Event.user_id)

    return render_template("showall.html", events=events)


@views.route("/showRock")
def rock():
    events = Event.query.select_from(Event).filter(Event.genre == "Rock")
    return render_template("showall.html", events=events)


@views.route("/showMetal")
def metal():
    events = Event.query.select_from(Event).filter(Event.genre == "Metal")
    return render_template("showall.html", events=events)


@views.route("/showRap")
def rap():
    events = Event.query.select_from(Event).filter(Event.genre == "Rap")
    return render_template("showall.html", events=events)


@views.route("/showPop")
def pop():
    events = Event.query.select_from(Event).filter(Event.genre == "Pop")
    return render_template("showall.html", events=events)


@views.route("/search")
def search():
    if request.args["search"]:
        print(request.args["search"])
        evnt = "%" + request.args["search"] + "%"
        events = Event.query.filter(Event.name.like(evnt)).all()
        return render_template("showall.html", events=events)
    else:
        return redirect(url_for("main.index"))

IAB207/Assessment3/website/templates/buy.html
{% from 'bootstrap5/form.html' import render_form %}
{% extends 'layout.html' %}
{% block title %} Purchase a Ticket {% endblock %}
{% block main %}
    <body style="background: #212529">
    <div class="container" style="color: #ffffff">
{#        <h1>Tickets for {{event.name}}</h1>#}
{#        <div class="eventinformation">#}
{#                <h2 class="eventdate"></h2><h3 class="eventtitle">At {{event.location}} on {{event.date}}</h3><br>#}
{#                <h2 class="eventtime"></h2><h3 class="eventtitle">Gates Open: {{event.time}}</h3><br>#}
{#                <h2 class="eventtime"></h2><h3 class="eventtitle">Category: {{event.genre}}</h3><br>#}
{#              </div>#}
{#    </div>#}
{#    <div class="container" style="color: white">#}
{#        <form action="{{ url_for('event.create') }}" method="post" enctype="multipart/form-data">#}
{#            {{ render_form(form, form_type='basic') }}#}


{#            # Rendering Option 2#}
{#          <div class="form-group">#}
{#            {{ form.name.label() }}#}
{#            {{ form.name() }}#}
{#          </div>#}
{#          <div class="form-group">#}
{#            {{ form.price.label() }}#}
{#            {{ form.price() }}#}
{#          </div>#}
{#		  		  		  		 <div class="form-group">#}
{#            {{ form.available.label()}}#}
{#            {{ form.available()}}#}
{#          </div>#}
{#          <div class="form-group">#}
{#            {{ form.date.label() }}#}
{#            {{ form.date() }}#}
{#          </div>#}
{#          <div class="form-group">#}
{#            {{ form.time.label()}}#}
{#            {{ form.time()}}#}
{#          </div>#}
{#		 <div class="form-group">#}
{#            {{ form.overview.label()}}#}
{#            {{ form.overview()}}#}
{#          </div>#}
{#		  		 <div class="form-group">#}
{#            {{ form.description.label()}}#}
{#            {{ form.description()}}#}
{#          </div>#}
{#		  		 <div class="form-group">#}
{#            {{ form.purchaseinfo.label()}}#}
{#            {{ form.purchaseinfo()}}#}
{#          </div>#}
{#		  		 <div class="form-group">#}
{#            {{ form.location.label()}}#}
{#            {{ form.location()}}#}
{#          </div>#}
{#		  		  		 <div class="form-group">#}
{#            {{ form.genre.label()}}#}
{#            {{ form.genre()}}#}
{#          </div>#}
{#		  		  		 <div class="form-group">#}
{#            {{ form.image.label()}}#}
{#            {{ form.image()}}#}
{#          </div>#}
{#		   <div class="form-group">#}
{#            {{ form.featured.label()}}#}
{#            {{ form.featured()}}#}
{#          </div>#}
{#          <br>#}
{#          <div id="success"></div>#}
{#          <div class="form-group">#}
{#            {{form.create()}}#}
{#          </div>#}
{#      </form>#}

{#          <div class="errors">#}
{#                    {% for field, ers in error %}#}
{#    {{ ', '.join(ers) }}#}
{#    {% endfor %}#}
{#            </div>#}
    </div>
   {% endblock %}

IAB207/Assessment3/website/templates/create.html
{% from 'bootstrap5/form.html' import render_form %}
{% extends 'layout.html' %}
{% block title %} Create an event {% endblock %}
{% block main %}
    <body style="background: #212529">
    <div class="container" style="color: #ffffff">
        <h1>Event Creation</h1>
        {% if msg != "" %}
        <h3 style="color:springgreen;">{{ msg }}</h3>
        {% endif %}
    </div>
    <div class="container" style="color: white">
        <form action="{{ url_for('event.create') }}" method="post" enctype="multipart/form-data">
            {{ render_form(form, form_type='basic') }}


{#            # Rendering Option 2#}
{#          <div class="form-group">#}
{#            {{ form.name.label() }}#}
{#            {{ form.name() }}#}
{#          </div>#}
{#          <div class="form-group">#}
{#            {{ form.price.label() }}#}
{#            {{ form.price() }}#}
{#          </div>#}
{#		  		  		  		 <div class="form-group">#}
{#            {{ form.available.label()}}#}
{#            {{ form.available()}}#}
{#          </div>#}
{#          <div class="form-group">#}
{#            {{ form.date.label() }}#}
{#            {{ form.date() }}#}
{#          </div>#}
{#          <div class="form-group">#}
{#            {{ form.time.label()}}#}
{#            {{ form.time()}}#}
{#          </div>#}
{#		 <div class="form-group">#}
{#            {{ form.overview.label()}}#}
{#            {{ form.overview()}}#}
{#          </div>#}
{#		  		 <div class="form-group">#}
{#            {{ form.description.label()}}#}
{#            {{ form.description()}}#}
{#          </div>#}
{#		  		 <div class="form-group">#}
{#            {{ form.purchaseinfo.label()}}#}
{#            {{ form.purchaseinfo()}}#}
{#          </div>#}
{#		  		 <div class="form-group">#}
{#            {{ form.location.label()}}#}
{#            {{ form.location()}}#}
{#          </div>#}
{#		  		  		 <div class="form-group">#}
{#            {{ form.genre.label()}}#}
{#            {{ form.genre()}}#}
{#          </div>#}
{#		  		  		 <div class="form-group">#}
{#            {{ form.image.label()}}#}
{#            {{ form.image()}}#}
{#          </div>#}
{#		   <div class="form-group">#}
{#            {{ form.featured.label()}}#}
{#            {{ form.featured()}}#}
{#          </div>#}
{#          <br>#}
{#          <div id="success"></div>#}
{#          <div class="form-group">#}
{#            {{form.create()}}#}
{#          </div>#}
      </form>

          <div class="errors">
                    {% for field, ers in error %}
    {{ ', '.join(ers) }}
    {% endfor %}
            </div>
    </div>
   {% endblock %}

IAB207/Assessment3/website/templates/error.html
{% extends "layout.html" %}
{% block title %} {{ error_number }} {% endblock %}
{% block main %}
      <body style="background: #212529">
    <div>
            <section class="position-relative py-4 py-xl-5">
                <div class="container">
                    <div class="row mb-5">
                        <div class="col-md-8 col-xl-6 text-center mx-auto offset-md-2" style="color:white">
                                   <h1>Oops... {{ error_number }}</h1>
                            <h2>{{ error_message }}</h2>
                        </div>
                    </div>
                    <div class="row mb-5">
                        <div class="col-md-8 col-xl-6 text-center mx-auto offset-md-2">
                            {% if error_number == "401" %}
                            <a
                                class="btn btn-primary btn-lg me-2"
                                role="button"
                                href="{{ url_for('auth.login')}}"
                                >Login</a>
                            {% endif %}
                            <a
                                class="btn btn-primary btn-lg me-2"
                                role="button"
                                href="{{ url_for('main.index')}}"
                                >Back to home</a>
                        </div>
                    </div>
                </div>
            </section>
        </div>

{% endblock %}

IAB207/Assessment3/website/templates/histroy.html
{% extends 'layout.html' %}
{% block title %} {{ current_user.username }} History {% endblock %}
{% block main %}

<body style="background: #212529;color: #ffffff;">
    <div class="container text-white py-4 py-xl-5">
        <div class="row mb-5" style="color: rgb(255, 255, 255)">
          <div class="col-md-8 col-xl-6 text-center mx-auto">
            <h2>Your history</h2>
          </div>
        </div>
   {#Purchase history comes here#}     <ul class="list-group list-group-flush">
  <li class="list-group-item">Cras justo odio</li>
  <li class="list-group-item">Dapibus ac facilisis in</li>
  <li class="list-group-item">Morbi leo risus</li>
  <li class="list-group-item">Porta ac consectetur ac</li>
  <li class="list-group-item">Vestibulum at eros</li>
</ul>


            </div>
</body>

{% endblock %}

IAB207/Assessment3/website/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
    />
    <title>{% block title %} {% endblock %} - Music Hub</title>
    <link rel="stylesheet" href="../bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="../css/styles.css" />
  </head>
<body>
{% include 'navbar.html' %}
{% block main %}
{% endblock %}
<footer class="text-center bg-dark">
      <div class="container text-white py-4 py-lg-5">
        <ul class="list-inline">
          <li class="list-inline-item me-4">
            <a class="link-light" href="https://github.com/braydannewman"
              >Movies</a
            >
          </li>
          <li class="list-inline-item me-4">
            <a class="link-light" href="https://github.com/braydannewman"
              >Music</a
            >
          </li>
          <li class="list-inline-item">
            <a class="link-light" href="https://github.com/braydannewman"
              >Water Bottles</a
            >
          </li>
        </ul>
        <ul class="list-inline">
          <li class="list-inline-item me-4">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="1em"
              height="1em"
              fill="currentColor"
              viewBox="0 0 16 16"
              class="bi bi-facebook text-light"
            >
              <path
                d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"
              ></path>
            </svg>
          </li>
          <li class="list-inline-item me-4">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="1em"
              height="1em"
              fill="currentColor"
              viewBox="0 0 16 16"
              class="bi bi-spotify text-light"
            >
              <path
                d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.669 11.538a.498.498 0 0 1-.686.165c-1.879-1.147-4.243-1.407-7.028-.77a.499.499 0 0 1-.222-.973c3.048-.696 5.662-.397 7.77.892a.5.5 0 0 1 .166.686zm.979-2.178a.624.624 0 0 1-.858.205c-2.15-1.321-5.428-1.704-7.972-.932a.625.625 0 0 1-.362-1.194c2.905-.881 6.517-.454 8.986 1.063a.624.624 0 0 1 .206.858zm.084-2.268C10.154 5.56 5.9 5.419 3.438 6.166a.748.748 0 1 1-.434-1.432c2.825-.857 7.523-.692 10.492 1.07a.747.747 0 1 1-.764 1.288z"
              ></path>
            </svg>
          </li>
          <li class="list-inline-item me-4">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="1em"
              height="1em"
              fill="currentColor"
              viewBox="0 0 16 16"
              class="bi bi-github text-light"
            >
              <path
                d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"
              ></path>
            </svg>
          </li>
          <li class="list-inline-item me-4">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="1em"
              height="1em"
              fill="currentColor"
              viewBox="0 0 16 16"
              class="bi bi-twitch text-light"
            >
              <path
                d="M3.857 0 1 2.857v10.286h3.429V16l2.857-2.857H9.57L14.714 8V0H3.857zm9.714 7.429-2.285 2.285H9l-2 2v-2H4.429V1.143h9.142v6.286z"
              ></path>
              <path
                d="M11.857 3.143h-1.143V6.57h1.143V3.143zm-3.143 0H7.571V6.57h1.143V3.143z"
              ></path>
            </svg>
          </li>
          <li class="list-inline-item me-4">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="1em"
              height="1em"
              fill="currentColor"
              viewBox="0 0 16 16"
              class="bi bi-twitter text-light"
            >
              <path
                d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"
              ></path>
            </svg>
          </li>
          <li class="list-inline-item">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="1em"
              height="1em"
              fill="currentColor"
              viewBox="0 0 16 16"
              class="bi bi-instagram text-light"
            >
              <path
                d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"
              ></path>
            </svg>
          </li>
        </ul>
        <p class="text-muted mb-0">Copyright © 2022 Music Hub</p>
      </div>
    </footer>
    <script src="../bootstrap/js/bootstrap.min.js"></script>
  </body>
</html>

IAB207/Assessment3/website/templates/login.html
{% from 'bootstrap5/form.html' import render_form %}
{% extends 'layout.html' %}
{% block title %} Login {% endblock %}
{% block main %}
    <body style="background: #212529;color: #ffffff;">
    <section class="position-relative py-4 py-xl-5">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h2>Log in</h2>
                </div>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 col-xl-4">
                    <div class="card mb-5" style="background: #191e24;">
                        <div class="card-body d-flex flex-column align-items-center">
                            <div class="bs-icon-xl bs-icon-circle bs-icon-primary bs-icon my-4">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                                     viewBox="0 0 16 16" class="bi bi-person">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
                                </svg>
                            </div>
                            <form class="text-center" method="post" action="{{ url_for('auth.login') }}">
                                {{ render_form(form) }}
                                <div class="errors">
                                    {% if error %}
                                        <p>{{ error }}</p>
                                    {% endif %}
                                </div>

                            </form>
                            <p style="margin-top:20px;">or <a href="{{ url_for('auth.register') }}"
                                                              style="color: #0a58ca;font-size:18px">Register here</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

IAB207/Assessment3/website/templates/navbar.html
<div class="m-4">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand d-flex align-items-center" href="{{ url_for('main.index') }}"
        ><span
                class="bs-icon-sm bs-icon-rounded bs-icon-primary d-flex justify-content-center align-items-center me-2 bs-icon"
        ><svg
                xmlns="http://www.w3.org/2000/svg"
                width="1em"
                height="1em"
                fill="currentColor"
                viewBox="0 0 16 16"
                class="bi bi-soundwave"
        >
              <path
                      fill-rule="evenodd"
                      d="M8.5 2a.5.5 0 0 1 .5.5v11a.5.5 0 0 1-1 0v-11a.5.5 0 0 1 .5-.5zm-2 2a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zm4 0a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zm-6 1.5A.5.5 0 0 1 5 6v4a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm8 0a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm-10 1A.5.5 0 0 1 3 7v2a.5.5 0 0 1-1 0V7a.5.5 0 0 1 .5-.5zm12 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0V7a.5.5 0 0 1 .5-.5z"
              ></path></svg></span
        ><span>Music Hub</span></a
        >
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navbarCollapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a href="{{ url_for('main.index') }}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Events</a>
                        <div class="dropdown-menu">
                            <a href="{{ url_for('main.rock') }}" class="dropdown-item">Rock</a>
                            <a href="{{ url_for('main.metal') }}" class="dropdown-item">Metal</a>
                            <a href="{{ url_for('main.rap') }}" class="dropdown-item">Rap</a>
                            <a href="{{ url_for('main.pop') }}" class="dropdown-item">Pop</a>
                            <div class="dropdown-divider"></div>
                            <a href="{{ url_for('main.all') }}"class="dropdown-item">View all</a>
                        </div>
                    </li>					
                </ul>
                <ul class="nav navbar-nav ms-auto">
                    <li class="nav-item dropdown">                       
					 {% if current_user.is_authenticated %}
                     	<a href="{{ url_for('auth.login') }}" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Hi {{ current_user.username }}!</a>
                        <div class="dropdown-menu dropdown-menu-end">
						    <a href="{{ url_for('event.create') }}" class="dropdown-item">Create an Event </a>
                            <a href="{{ url_for('main.my') }}" class="dropdown-item">My Events</a>
                            <a href="{{ url_for('history.myhistory') }}" class="dropdown-item">Booking History</a>
                            <div class="dropdown-divider"></div>
                            <a href="{{ url_for('auth.logout') }}" class="dropdown-item">Logout</a>
                        </div>
						{% else %}
                        <li class="nav-item">
                           <a href="{{ url_for('auth.login') }}" class="nav-link">Login</a>
                        </li>
                        <li class="nav-item">
                           <a href="{{ url_for('auth.register') }}" class="nav-link">Register</a>
                        </li>
                        {% endif %}
                        <li class="nav-item d-flex flex-nowrap">
                            <form class="form-inline d-flex flex-nowrap align-items-center" action="{{url_for('main.search')}}" >
                                <input type="text" name="search" class="form-control flex-grow-1 my-1" id="SearchForm">
                                <button type="submit" class="flex-shrink-1 btn btn-primary my-1">Submit</button>
                            </form>
                        </li>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>

IAB207/Assessment3/website/templates/register.html
{% from 'bootstrap5/form.html' import render_form %}
{% extends 'layout.html' %}
{% block title %} Register {% endblock %}
{% block main %}
    <body style="background: #212529;color: #ffffff;">
    <section class="position-relative py-4 py-xl-5">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h2>Register</h2>
                </div>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 col-xl-4">
                    <div class="card mb-5" style="background: #191e24;">
                        <div class="card-body d-flex flex-column align-items-center">
                            <div class="bs-icon-xl bs-icon-circle bs-icon-primary bs-icon my-4">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                                     viewBox="0 0 16 16" class="bi bi-person">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
                                </svg>
                            </div>
                            <form class="text-center" method="post" action="{{ url_for('auth.register') }}">
                                {{ render_form(form) }}
                                <div class="errors">
                                    {% if error %}
                                        <p>{{ error }}</p>
                                    {% endif %}
                                </div>
                            </form>
                         <p style="margin-top:20px;">Already have an account? <a href="{{ url_for('auth.login') }}"
                                                              style="color: #0a58ca;font-size:18px">Login here</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}